return {
  diagnostic_icons = {
    error = "",
    warning = "",
    info = "",
    hint = "",
    check = "",
    question = "",
    open = "",
    fill = "",
    bold_error = "",
    bold_warning = "",
    bold_info = "",
    bold_hint = "",
    bold_check = "",
    bold_question = "",
    bold_open = "",
  },
  modeline_icons = {
    mode = "",
    evil = "",
    tab = "",
    save = "",
    lock = "",
    new_file = "",
    checkbox_blank = "",
    term = "",
  },
  git_icons = {
    added = "",
    modified = "",
    removed = "",
    bold_added = "",
    bold_modified = "",
    bold_removed = "",
    branch = "",
    gutter_removed = "契",
    gutter_top_removed = "",
    -- gutter = "▎",
    gutter = "▍",
  },
}
