return {
  task_icons = {
    -- 
    -- 
    -- 
    running = "",
    success = "",
    failure = "",
    cancelled = "󰜺",
  },
  diagnostic_icons = {
    error = "",
    warning = "",
    info = "",
    hint = "",
    check = "",
    question = "",
    open = "",
    fill = "",
    bold_error = "",
    bold_warning = "",
    bold_info = "",
    bold_hint = "",
    bold_check = "",
    bold_question = "",
    bold_open = "",
  },
  modeline_icons = {
    mode = "",
    evil = "",
    tab = "",
    save = "",
    lock = "",
    new_file = "",
    checkbox_blank = "",
    term = "",
    hook = "󰛢",
    tag = "",
  },
  git_icons = {
    added = "",
    modified = "",
    removed = "",
    bold_added = "",
    bold_modified = "",
    -- bold_modified = "󱗜",
    bold_removed = "",
    copied = ">",
    renamed = "➡",
    unmerged = "‡",
    untracked = "?",
    branch = "",
    gutter_removed = "契",
    gutter_top_removed = "",
    -- gutter = "▎",
    gutter = "▍",
  },
  dap_icons = { breakpoint = "ﴫ", log_point = "", stopped = "" },
  misc = {
    expanded = "",
    collapsed = "",
    folder_empty = "󱧴",
    folder_closed = "",
    folder_open = "",
    file = "",
    v_border = "▐",
  },
  mode_colors = {
    ["i"] = "#a9b665",
    ["c"] = "#d8a657",
    ["t"] = "#ea6962",
    ["v"] = "#d4879c",
    ["V"] = "#d4879c",
    [""] = "#d4879c",
    [""] = "#d4879c",
  },
  kinds = {
    Array = " ",
    Boolean = "󰨙 ",
    Class = " ",
    Codeium = "󰘦 ",
    Color = " ",
    Control = " ",
    Collapsed = " ",
    Constant = "󰏿 ",
    Constructor = " ",
    Copilot = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = "󰊕 ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = "󰊕 ",
    Module = " ",
    Namespace = "󰦮 ",
    Null = " ",
    Number = "󰎠 ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = "󰆼 ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
}
