return {
  { "rcarriga/nvim-notify", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "windwp/nvim-spectre", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "echasnovski/mini.surround", enabled = false },
  { "echasnovski/mini.bufremove", enabled = false },
  { "catppuccin/nvim", enabled = false },
  { "catppuccin", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  { "folke/flash.nvim", keys = { { "R", mode = { "o", "x" }, false }, { "S", mode = { "n", "o", "x" }, false } } },
  { "LazyVim/LazyVim", opts = { defaults = { keymaps = false } } },
  { "folke/noice.nvim", enabled = false },
}
